### ISSUE TITLE
Doesn't work on forge 1.19.2

### ISSUE THREAD

**Issue by Meowmeowmeowmeowah** [plasmoapp/pv-addon-replaymod#5]
**Bug description**
Doesn't start up, Error code -1

**Steps to reproduce the issue**
1. Download [Replay Mod 1.19.2](https://www.curseforge.com/minecraft/mc-mods/replaymod-for-forge-reborn)
2. Download PV-Addon-Replaymod
3. Start Minecraft

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.19.2
- Forge version: 43.3.5

**Comment by apehum** [comment]
Forge is not supported. I've removed misleading description on github and modrinth.
