### ISSUE TITLE
1.21 please

### ISSUE THREAD

**Issue by mihalera** [plasmoapp/pv-addon-replaymod#6]
[crash-2024-07-19_08.11.06.3821-quilt_loader.txt](https://github.com/user-attachments/files/16302409/crash-2024-07-19_08.11.06.3821-quilt_loader.txt)

**Versions**
- Minecraft version 1.21
- Quilt version 0.26.3
- Plasmo Voice version 2.0.10
- ReplayMod Version 2.6.17
- Mod version 2.1.0

**Comment by apehum** [comment]
Try with this pre-release: https://github.com/plasmoapp/pv-addon-replaymod/releases/tag/2.0.1

**Comment by mihalera** [comment]
Thanks

**Comment by mihalera** [comment]
[crash-2024-07-24_12.03.03-client.txt](https://github.com/user-attachments/files/16359901/crash-2024-07-24_12.03.03-client.txt)

**Comment by apehum** [comment]
This crash is not related to pv-addon-replaymod.
If you still have any issues, re-open the issue and provide a full client log file.
